import writePrettierFile from 'write-prettier-file'
import {encode} from '../src/utils.js'
import getData from './get-data.js'

const PROJECT_ROOT = new URL('../', import.meta.url)
const SCRIPT_FILE = import.meta.url.slice(PROJECT_ROOT.href.length)

const {current, outdated} = await getData()

const head = `
/*
DO NOT EDIT THIS FILE

Auto generated by script \`../${SCRIPT_FILE}\`
*/
`

await writePrettierFile(
  new URL('./src/raw-currency-data.js', PROJECT_ROOT),
  `
    ${head}

    const current = ${JSON.stringify(encode(current))}
    const all = current + ${JSON.stringify(encode(outdated))}

    export default current
    export {all}
  `,
  {parser: 'meriyah'},
)
await writePrettierFile(
  new URL('./src/currencies.js', PROJECT_ROOT),
  `
    ${head}

    const current = ${JSON.stringify(current)}
    const outdated = ${JSON.stringify(outdated)}

    const all = [...current, ...outdated]
    export default current
    export {all}
  `,
  {parser: 'meriyah'},
)
