import writePrettierFile from 'write-prettier-file'
import getData from './get-data.js'

const PROJECT_ROOT = new URL('../', import.meta.url)
const SCRIPT_FILE = import.meta.url.slice(PROJECT_ROOT.href.length)

const LOWERCASE_A_CODEPOINT = 'a'.codePointAt(0)
const UPPERCASE_A_CODEPOINT = 'A'.codePointAt(0)
const charactersNeedEncode = new Map(
  [
    // 0-9
    ...Array.from({length: 10}, (_, index) => String(index)),
    // a-f
    ...Array.from({length: 6}, (_, index) =>
      String.fromCodePoint(index + LOWERCASE_A_CODEPOINT),
    ),
    // A-Z
    ...Array.from({length: 26}, (_, index) =>
      String.fromCodePoint(index + UPPERCASE_A_CODEPOINT),
    ),
  ].map((character) => [
    character,
    character.codePointAt(0).toString(16).padStart(2, '0'),
  ]),
)

const encodeName = (name) =>
  [...name]
    .map((character) =>
      charactersNeedEncode.has(character)
        ? charactersNeedEncode.get(character)
        : character,
    )
    .join('')
const dataToText = (currencies) =>
  currencies.map(({code, name}) => `${code}${encodeName(name)}`).join('')

const {current, outdated} = await getData()

const head = `
/*
DO NOT EDIT THIS FILE

Auto generated by script \`${SCRIPT_FILE}\`
*/
`

await writePrettierFile(
  new URL('./raw-currency-data.js', PROJECT_ROOT),
  `
    ${head}

    export default ${JSON.stringify([
      dataToText(current),
      dataToText(outdated),
    ])}
  `,
  {parser: 'meriyah'},
)
await writePrettierFile(
  new URL('./currencies.js', PROJECT_ROOT),
  `
    ${head}

    export const current = ${JSON.stringify(current)};
    export const outdated = ${JSON.stringify(outdated)};
    export const all = [...current, ...outdated]
  `,
  {parser: 'meriyah'},
)
