import writePrettierFile from 'write-prettier-file'
import getData from './get-data.js'

const PROJECT_ROOT = new URL('../', import.meta.url)
const SCRIPT_FILE = import.meta.url.slice(PROJECT_ROOT.href.length)

const dataToText = (currencies) =>
  currencies.map(({code, name}) => `${code}${name}`).join(',')

const {current, outdated} = await getData()

const head = `
/*
DO NOT EDIT THIS FILE

Auto generated by script \`${SCRIPT_FILE}\`
*/
`

await writePrettierFile(
  new URL('./currencies-raw.js', PROJECT_ROOT),
  `
  

  export default ${JSON.stringify([dataToText(current), dataToText(outdated)])};
`,
)
await writePrettierFile(
  new URL('./currencies.js', PROJECT_ROOT),
  `
  /*
  * DO NOT EDIT THIS FILE
  * 
  * Auto generated by script \`${SCRIPT_FILE}\`
  */

  export const current = ${JSON.stringify(current)};
  export const outdated = ${JSON.stringify(outdated)};
`,
)
